-- TODO: Move this to a reports module
-- function Work.print_work_item(work_item)
-- 	io.write(string.format("%3s - %-40s %s\n", work_item.id,
-- 	                       work_item.name, work_item:get_estimate_string()))
-- end
-- 
-- function Work.print_work_items(work_items)
-- 	for i = 1,#work_items do
-- 		if type(work_items[i]) == "string" then
-- 			print(work_items[i])
-- 		else
-- 			Work.print_work_item(work_items[i])
-- 		end
-- 	end
-- end

